#!/usr/bin/env bash
# Change localhost from 127.0.0.2  
#+ to facebook.com to 8.8.8.8

cp /etc/hosts ~/hosts.new
sed -i "s/.*localhost$/127.0.0.2    localhost/g" ~/hosts.new
sed -i "s/.*facebook.com//g" ~/hosts.new
echo "8.8.8.8   facebook.com" >> ~/hosts.new
cat ~/hosts.new > /etc/hosts
